import turtle
turtle.speed(2)
turtle.bgcolor("black")
turtle.color("red")

#1st part of V (i.e \)
turtle.begin_fill()
turtle.color("red")
turtle.right(50)
turtle.forward(100)
turtle.right(130)
turtle.forward(100)
turtle.right(50)
turtle.forward(200)
turtle.right(40)
turtle.forward(120)
turtle.right(140)
turtle.forward(256)
turtle.end_fill()

#2nd part of V (i.e /)
turtle.begin_fill()
turtle.color("red")
turtle.penup()
turtle.left(95)
turtle.pendown()
turtle.penup()
turtle.forward(30)
turtle.pendown()
turtle.forward(250)
turtle.right(135)
turtle.forward(120)
turtle.right(45)
turtle.forward(83)
turtle.right(45)
turtle.forward(120)
turtle.end_fill()

#border of logo (i.e [v])
turtle.penup()
turtle.backward(250)
turtle.right(90)
turtle.pendown()
turtle.pensize(10)
turtle.forward(250)
turtle.left(90)
turtle.forward(500)
turtle.left(90)
turtle.forward(420)
turtle.left(90)
turtle.forward(500)
turtle.left(90)
turtle.forward(200)
turtle.right(90)
turtle.penup()
turtle.forward(130)

#text
turtle.right(90)
turtle.forward(300)
turtle.right(90)
turtle.forward(500)
style = ('VALORANT', 30, 'bold')
turtle.write("VALORANT",font=style)
turtle.penup()
turtle.backward(500)

#done by (XD)
turtle.color("cyan")
style=('Comic Sans MS',20,'italic')
turtle.write("xLACHLANx",font=style)
turtle.pendown()
turtle.pensize(0)
turtle.backward(156)
turtle.penup()
turtle.backward(3000)

turtle.done()